site_name: Pelis
nav:
  - Home: index.md
  - Interestelar: interestelar.md
  - Avatar: avatar.md
  - Titanic: titanic.md
  - Hook: hook.md
  - Dragonball Evolution: dragoncacas.md
theme: readthedocs
markdown_extensions:
  - attr_list