site_name: Pelis

nav:
  - Home: index.md
  - Interestelar: interestelar.md
  - Avatar: avatar.md
  - Titanic: titanic.md
  - Hook: hook.md
  - Posiblemente el peor live action de la historia: dragoncacas.md
  - About: about.md

theme:
  name: material
  favicon: img/favicon.png

markdown_extensions:
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/
      name: Instagram
    - icon: fontawesome/brands/github
      link: https://github.com/PabloGomezB/pelis
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
      name: Twitter
    - icon: fontawesome/brands/docker
      link: https://www.docker.com/
      name: Docker
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/
      name: Linkedin

copyright: Copyright &copy; 2020 - 2020 Pablo Gomez